apiVersion: v1
items:
- apiVersion: v1
  data:
    redis-password: bFhYa1ozMDBGVw==
  kind: Secret
  metadata:
    labels:
      app: redis
      chart: redis-12.2.3
      heritage: Tiller
      release: tensorsec-cache
    name: tensorsec-cache-redis
  type: Opaque
- apiVersion: v1
  data:
    config.yaml: Y2xhaXI6CiAgZGF0YWJhc2U6CiAgICAjIERhdGFiYXNlIGRyaXZlci4KICAgIHR5cGU6IHBnc3FsCiAgICBvcHRpb25zOgogICAgICAjIFBvc3RncmVTUUwgQ29ubmVjdGlvbiBzdHJpbmcuCiAgICAgICMgaHR0cHM6Ly93d3cucG9zdGdyZXNxbC5vcmcvZG9jcy9jdXJyZW50L3N0YXRpYy9saWJwcS1jb25uZWN0Lmh0bWwjTElCUFEtQ09OTlNUUklORwogICAgICBzb3VyY2U6ICJwb3N0Z3JlczovL3Bvc3RncmVzOnBhc3N3b3JkQHRlbnNvcnNlYy1wb3N0Z3Jlc3FsOjU0MzIvcG9zdGdyZXM/c3NsbW9kZT1kaXNhYmxlIgogICAgICAKCiAgICAgICMgTnVtYmVyIG9mIGVsZW1lbnRzIGtlcHQgaW4gdGhlIGNhY2hlLgogICAgICAjIFZhbHVlcyB1bmxpa2VseSB0byBjaGFuZ2UgKGUuZy4gbmFtZXNwYWNlcykgYXJlIGNhY2hlZCBpbiBvcmRlciB0byBzYXZlIHByZXZlbnQgbmVlZGxlc3Mgcm91bmR0cmlwcyB0byB0aGUgZGF0YWJhc2UuCiAgICAgIGNhY2hlc2l6ZTogMTYzODQKCiAgICAgICMgMzItYml0IFVSTC1zYWZlIGJhc2U2NCBrZXkgdXNlZCB0byBlbmNyeXB0IHBhZ2luYXRpb24gdG9rZW5zLgogICAgICAjIElmIG9uZSBpcyBub3QgcHJvdmlkZWQsIGl0IHdpbGwgYmUgZ2VuZXJhdGVkLgogICAgICAjIE11bHRpcGxlIGNsYWlyIGluc3RhbmNlcyBpbiB0aGUgc2FtZSBjbHVzdGVyIG5lZWQgdGhlIHNhbWUgdmFsdWUuCiAgICAgIHBhZ2luYXRpb25rZXk6ICJYeG9QdENVenJVdjRKVjVkUyt5UStNZFc3eUxFSm5STXdpZ1ZZL2JwZ3RRPSIKICBhcGk6CiAgICAjIHYzIGdycGMvUkVTVGZ1bCBBUEkgc2VydmVyIGFkZHJlc3MuCiAgICBhZGRyOiAiMC4wLjAuMDo2MDYwIgoKICAgICMgSGVhbHRoIHNlcnZlciBhZGRyZXNzLgogICAgIyBUaGlzIGlzIGFuIHVuZW5jcnlwdGVkIGVuZHBvaW50IHVzZWZ1bCBmb3IgbG9hZCBiYWxhbmNlcnMgdG8gY2hlY2sgdG8gaGVhbHRoaW5lc3Mgb2YgdGhlIGNsYWlyIHNlcnZlci4KICAgIGhlYWx0aGFkZHI6ICIwLjAuMC4wOjYwNjEiCgogICAgIyBEZWFkbGluZSBiZWZvcmUgYW4gQVBJIHJlcXVlc3Qgd2lsbCByZXNwb25kIHdpdGggYSA1MDMuCiAgICB0aW1lb3V0OiA5MDBzCgogICAgIyBPcHRpb25hbCBQS0kgY29uZmlndXJhdGlvbi4KICAgICMgSWYgeW91IHdhbnQgdG8gZWFzaWx5IGdlbmVyYXRlIGNsaWVudCBjZXJ0aWZpY2F0ZXMgYW5kIENBcywgdHJ5IHRoZSBmb2xsb3dpbmcgcHJvamVjdHM6CiAgICAjIGh0dHBzOi8vZ2l0aHViLmNvbS9jb3Jlb3MvZXRjZC1jYQogICAgIyBodHRwczovL2dpdGh1Yi5jb20vY2xvdWRmbGFyZS9jZnNzbAogICAgc2VydmVybmFtZToKICAgIGNhZmlsZToKICAgIGtleWZpbGU6CiAgICBjZXJ0ZmlsZToKCiAgd29ya2VyOgogICAgbmFtZXNwYWNlX2RldGVjdG9yczoKICAgIC0gb3MtcmVsZWFzZQogICAgLSBsc2ItcmVsZWFzZQogICAgLSBhcHQtc291cmNlcwogICAgLSBhbHBpbmUtcmVsZWFzZQogICAgLSByZWRoYXQtcmVsZWFzZQoKICAgIGZlYXR1cmVfbGlzdGVyczoKICAgIC0gYXBrCiAgICAtIGRwa2cKICAgIC0gcnBtCgogIHVwZGF0ZXI6CiAgICAjIEZyZXF1ZW5jeSB0aGUgZGF0YWJhc2Ugd2lsbCBiZSB1cGRhdGVkIHdpdGggdnVsbmVyYWJpbGl0aWVzIGZyb20gdGhlIGRlZmF1bHQgZGF0YSBzb3VyY2VzLgogICAgIyBUaGUgdmFsdWUgMCBkaXNhYmxlcyB0aGUgdXBkYXRlciBlbnRpcmVseS4KICAgIGludGVydmFsOiAiNW0iCiAgICBlbmFibGVkdXBkYXRlcnM6CiAgICAtIGRlYmlhbgogICAgLSB1YnVudHUKICAgIC0gcmVkaGF0CiAgICAtIGFscGluZQogICAgLSByZWRoYXQKCiAgbm90aWZpZXI6CiAgICAjIE51bWJlciBvZiBhdHRlbXB0cyBiZWZvcmUgdGhlIG5vdGlmaWNhdGlvbiBpcyBtYXJrZWQgYXMgZmFpbGVkIHRvIGJlIHNlbnQuCiAgICBhdHRlbXB0czogMwoKICAgICMgRHVyYXRpb24gYmVmb3JlIGEgZmFpbGVkIG5vdGlmaWNhdGlvbiBpcyByZXRyaWVkLgogICAgcmVub3RpZnlpbnRlcnZhbDogMmgKCiAgICBodHRwOgogICAgICAjIE9wdGlvbmFsIGVuZHBvaW50IHRoYXQgd2lsbCByZWNlaXZlIG5vdGlmaWNhdGlvbnMgdmlhIFBPU1QgcmVxdWVzdHMuCiAgICAgIGVuZHBvaW50OiAiPG5vIHZhbHVlPiIKCiAgICAgICMgT3B0aW9uYWwgUEtJIGNvbmZpZ3VyYXRpb24uCiAgICAgICMgSWYgeW91IHdhbnQgdG8gZWFzaWx5IGdlbmVyYXRlIGNsaWVudCBjZXJ0aWZpY2F0ZXMgYW5kIENBcywgdHJ5IHRoZSBmb2xsb3dpbmcgcHJvamVjdHM6CiAgICAgICMgaHR0cHM6Ly9naXRodWIuY29tL2Nsb3VkZmxhcmUvY2Zzc2wKICAgICAgIyBodHRwczovL2dpdGh1Yi5jb20vY29yZW9zL2V0Y2QtY2EKICAgICAgc2VydmVybmFtZToKICAgICAgY2FmaWxlOgogICAgICBrZXlmaWxlOgogICAgICBjZXJ0ZmlsZToKCiAgICAgICMgT3B0aW9uYWwgSFRUUCBQcm94eTogbXVzdCBiZSBhIHZhbGlkIFVSTCAoaW5jbHVkaW5nIHRoZSBzY2hlbWUpLgogICAgICBwcm94eToK
  kind: Secret
  metadata:
    labels:
      app: tensorsec-clair
      chart: clair-0.1.3
      heritage: Tiller
      release: tensorsec
    name: tensorsec-clair
  type: Opaque
- apiVersion: v1
  data:
    mongodb-password: cmVkc3RvbmVNb25nbzEyMw==
    mongodb-replica-set-key: TXNwSXFUN0plOQ==
    mongodb-root-password: VFBERDhSbW9QTA==
  kind: Secret
  metadata:
    labels:
      app.kubernetes.io/component: mongodb
      app.kubernetes.io/instance: tensorsec-mongo
      app.kubernetes.io/managed-by: Tiller
      app.kubernetes.io/name: mongodb
      helm.sh/chart: mongodb-10.3.1
    name: tensorsec-mongo-mongodb
  type: Opaque
- apiVersion: v1
  data:
    postgresql-password: cGFzc3dvcmQ=
  kind: Secret
  metadata:
    labels:
      app: postgresql
      chart: postgresql-6.3.9
      heritage: Tiller
      release: tensorsec
    name: tensorsec-postgresql
  type: Opaque
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
