apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/instance: tensorsec-mongo
    app.kubernetes.io/managed-by: Tiller
    app.kubernetes.io/name: mongodb
    helm.sh/chart: mongodb-10.3.1
  name: tensorsec-mongo-mongodb
secrets:
- name: tensorsec-mongo-mongodb
