apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: redis
      chart: redis-12.2.3
      heritage: Tiller
      release: tensorsec-cache
    name: tensorsec-cache-redis-headless
  spec:
    clusterIP: None
    ports:
    - name: redis
      port: 6379
      protocol: TCP
      targetPort: redis
    selector:
      app: redis
      release: tensorsec-cache
    sessionAffinity: None
    type: ClusterIP
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: redis
      chart: redis-12.2.3
      heritage: Tiller
      release: tensorsec-cache
    name: tensorsec-cache-redis-master
  spec:
    clusterIP:
    ports:
    - name: redis
      port: 6379
      protocol: TCP
      targetPort: redis
    selector:
      app: redis
      release: tensorsec-cache
      role: master
    sessionAffinity: None
    type: ClusterIP
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: tensorsec-clair
      chart: clair-0.1.3
      heritage: Tiller
      release: tensorsec
    name: tensorsec-clair
  spec:
    clusterIP:
    ports:
    - name: clair-api
      port: 6060
      protocol: TCP
      targetPort: 6060
    - name: clair-health
      port: 6061
      protocol: TCP
      targetPort: 6061
    selector:
      app: tensorsec-clair
    sessionAffinity: None
    type: ClusterIP
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app.kubernetes.io/component: arbiter
      app.kubernetes.io/instance: tensorsec-mongo
      app.kubernetes.io/managed-by: Tiller
      app.kubernetes.io/name: mongodb
      helm.sh/chart: mongodb-10.3.1
    name: tensorsec-mongo-mongodb-arbiter-headless
  spec:
    clusterIP: None
    ports:
    - name: tcp-mongodb
      port: 27017
      protocol: TCP
      targetPort: mongodb
    selector:
      app.kubernetes.io/component: arbiter
      app.kubernetes.io/instance: tensorsec-mongo
      app.kubernetes.io/name: mongodb
    sessionAffinity: None
    type: ClusterIP
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app.kubernetes.io/component: mongodb
      app.kubernetes.io/instance: tensorsec-mongo
      app.kubernetes.io/managed-by: Tiller
      app.kubernetes.io/name: mongodb
      helm.sh/chart: mongodb-10.3.1
    name: tensorsec-mongo-mongodb-headless
  spec:
    clusterIP: None
    ports:
    - name: mongodb
      port: 27017
      protocol: TCP
      targetPort: mongodb
    publishNotReadyAddresses: true
    selector:
      app.kubernetes.io/component: mongodb
      app.kubernetes.io/instance: tensorsec-mongo
      app.kubernetes.io/name: mongodb
    sessionAffinity: None
    type: ClusterIP
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app.kubernetes.io/component: mongodb
      app.kubernetes.io/instance: tensorsec-db
      app.kubernetes.io/managed-by: Tiller
      app.kubernetes.io/name: mongodb
      helm.sh/chart: mongodb-10.3.1
    name: tensorsec-mongodb
  spec:
    clusterIP:
    ports:
    - port: 27017
      protocol: TCP
      targetPort: 27017
    selector:
      app.kubernetes.io/component: mongodb
      app.kubernetes.io/instance: tensorsec-mongo
      app.kubernetes.io/name: mongodb
    sessionAffinity: None
    type: ClusterIP
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: postgresql
      chart: postgresql-6.3.9
      heritage: Tiller
      release: tensorsec
    name: tensorsec-postgresql
  spec:
    clusterIP:
    ports:
    - name: postgresql
      port: 5432
      protocol: TCP
      targetPort: postgresql
    selector:
      app: postgresql
      release: tensorsec
      role: master
    sessionAffinity: None
    type: ClusterIP
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: scanner
      chart: scanner-0.1.0
      heritage: Tiller
      release: tensorsec
    name: tensorsec-scanner
  spec:
    clusterIP:
    ports:
    - name: api
      port: 8080
      protocol: TCP
      targetPort: 8080
    - name: scanner-layer
      port: 9278
      protocol: TCP
      targetPort: 9278
    selector:
      app.kubernetes.io/instance: tensorsec
      app.kubernetes.io/name: scanner
    sessionAffinity: None
    type: ClusterIP
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
